/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFileChooser;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import java.io.File;
import service.ATSService;
import service.RoleService;
import service.SuggestionService;
import db.DBConnection;

/**
 *
 * @author CHITTY
 */
public class ResumeAnalyzerUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ResumeAnalyzerUI.class.getName());

    /**
     * Creates new form ResumeAnalyzerUI
     */
    public ResumeAnalyzerUI() {
        initComponents();
         this.setSize(500, 400);
    this.setLocationRelativeTo(null);
      //f  getContentPane().setLayout(new java.awt.FlowLayout());

    }
  private void btnAnalyzeActionPerformed(java.awt.event.ActionEvent evt) {

        String resume = txtResume.getText();

        int score = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtResume = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnupload = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jButton1.setText("jButton1");

        jButton3.setText("jButton3");

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtResume.setColumns(20);
        txtResume.setRows(5);
        jScrollPane4.setViewportView(txtResume);

        jButton2.setText("Analyze Resume");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton4.setText("Save analysis");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        btnupload.setText("upload resume");
        btnupload.addActionListener(this::btnuploadActionPerformed);

        jTextField1.setText("AI Resume Analyzer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(198, 198, 198)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnupload)
                        .addGap(45, 45, 45)
                        .addComponent(jButton2)
                        .addGap(48, 48, 48)
                        .addComponent(jButton4)))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupload)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(2497, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 String resume = txtResume.getText().toLowerCase();  // ✅ ONLY ONCE

    int score = ATSService.calculateScore(resume);
    String role = RoleService.getRole(resume);
    String suggestions = SuggestionService.getSuggestions(resume);

    javax.swing.JOptionPane.showMessageDialog(this,
        "ATS Score: " + score +
        "\nRole: " + role +
        "\nSuggestions: " + suggestions
    );

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 try {

        String resume = txtResume.getText();

        int score = ATSService.calculateScore(resume);

        String role = RoleService.getRole(resume);

        String suggestions =
                SuggestionService.getSuggestions(resume);

        Connection con = DBConnection.getConnection();
if (con == null) {
    javax.swing.JOptionPane.showMessageDialog(
        this,
        "Database Connection Failed!"
    );
    return;
}
        PreparedStatement ps = con.prepareStatement(
            "INSERT INTO resumes (user_id, resume_text, ats_score, suggested_role, suggestions) VALUES (?, ?, ?, ?, ?)"
        );

        ps.setInt(1, 1); // demo user id

        ps.setString(2, resume);

        ps.setInt(3, score);

        ps.setString(4, role);

        ps.setString(5, suggestions);

        ps.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Resume Saved Successfully!"
        );

        ps.close();
        con.close();

    } catch (Exception e) {

        e.printStackTrace();

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuploadActionPerformed
JFileChooser chooser = new JFileChooser();

    int result = chooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {

        File file = chooser.getSelectedFile();

        javax.swing.JOptionPane.showMessageDialog(this,
                "Selected File:\n" + file.getAbsolutePath());

        try {

            PDDocument document = PDDocument.load(file);

            PDFTextStripper stripper = new PDFTextStripper();

            String text = stripper.getText(document);

            System.out.println("PDF TEXT:");
            System.out.println(text);

            txtResume.setText(text);

            document.close();

            javax.swing.JOptionPane.showMessageDialog(this,
                    "PDF Loaded Successfully!");

        } catch (Exception e) {

            e.printStackTrace();

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error:\n" + e.getMessage());

        }
    }
//File file = chooser.getSelectedFile();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnuploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ResumeAnalyzerUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnupload;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea txtResume;
    // End of variables declaration//GEN-END:variables
}
